services:
  # Application Service
  api:
    build: .
    container_name: jos-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RUST_LOG=${RUST_LOG:-info}
    networks:
      - jos-network
    restart: unless-stopped
    depends_on:
      - db
      - redis

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: jos-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - jos-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: jos-redis
    volumes:
      - redis_data:/data
    networks:
      - jos-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  jos-network:
    driver: bridge
