DROP TABLE IF EXISTS session_checkins CASCADE;
DROP TABLE IF EXISTS session_intents CASCADE;
DROP TABLE IF EXISTS table_requests CASCADE;
DROP TABLE IF EXISTS table_members CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS game_systems CASCADE;

DROP TYPE IF EXISTS session_status;
DROP TYPE IF EXISTS intent_status;
DROP TYPE IF EXISTS request_status;
DROP TYPE IF EXISTS table_status;
