//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, sqlx::FromRow)]
pub struct Model {
    pub id: Uuid,
    pub name: String,
    pub table_id: Uuid,
    pub accepting_intents: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
}
