//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::enums::EIntentStatus;
use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, sqlx::FromRow)]
pub struct Model {
    pub id: Uuid,
    pub user_id: Uuid,
    pub session_id: Uuid,
    pub intent_status: EIntentStatus,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
}
