name: Rust CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  ci:
    name: Build, Test, Lint, Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Cache cargo git
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-git-

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-build-

      - name: Build project
        run: cargo build --workspace --verbose

      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --workspace

      - name: Run clippy (lint)
        env:
          SQLX_OFFLINE: true
        run: cargo clippy --workspace -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build documentation
        run: cargo doc --no-deps --workspace --verbose
